//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPUWindowProgramming.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPUWindowProgramming.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BackGround {
            get {
                object obj = ResourceManager.GetObject("BackGround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BlueObject {
            get {
                object obj = ResourceManager.GetObject("BlueObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cClearObject {
            get {
                object obj = ResourceManager.GetObject("cClearObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cHpObject {
            get {
                object obj = ResourceManager.GetObject("cHpObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap GreenObject {
            get {
                object obj = ResourceManager.GetObject("GreenObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap HpMark {
            get {
                object obj = ResourceManager.GetObject("HpMark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   200	-300	1
        ///250	-350	0
        ///300	-400	2
        ///350	-450	1
        ///400	-500	0
        ///450	-550	0
        ///500	-600	1
        ///550	-650	2
        ///600	-700	1
        ///650	-750	2
        ///700	-800	1
        ///750	-850	2
        ///800	-900	0
        ///850	-950	2
        ///900	-1000	4
        ///50	-1000	0
        ///100	-950	1
        ///150	-900	2
        ///200	-850	0
        ///250	-800	1
        ///300	-750	2
        ///350	-700	0
        ///400	-650	1
        ///450	-600	2
        ///500	-550	0
        ///550	-500	1
        ///600	-450	2
        ///650	-400	0
        ///700	-350	1
        ///750	-300	2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern0 {
            get {
                return ResourceManager.GetString("Pattern0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50	-100	1
        ///150	-300	2
        ///250	-100	0
        ///350	-300	0
        ///450	-100	1
        ///550	-300	0
        ///650	-100	2
        ///750	-300	0
        ///850	-100	0
        ///950	-300	1
        ///50	-400	2
        ///150	-600	1
        ///250	-400	0
        ///350	-600	0
        ///450	-400	2
        ///550	-600	1
        ///650	-400	0
        ///750	-600	2
        ///850	-400	2
        ///950	-600	0
        ///50	-700	2
        ///150	-900	0
        ///250	-700	1
        ///350	-900	0
        ///450	-700	2
        ///550	-900	2
        ///650	-700	0
        ///750	-900	0
        ///850	-700	1
        ///950	-900	2
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern1 {
            get {
                return ResourceManager.GetString("Pattern1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50	-100	0
        ///150	-300	2
        ///250	-100	1
        ///350	-300	0
        ///450	-100	1
        ///550	-300	2
        ///650	-100	1
        ///750	-300	1
        ///850	-100	2
        ///950	-300	0
        ///50	-400	1
        ///150	-600	2
        ///250	-400	2
        ///350	-600	1
        ///450	-400	3
        ///550	-600	1
        ///650	-400	0
        ///750	-600	2
        ///850	-400	1
        ///950	-600	1
        ///50	-700	2
        ///150	-900	1
        ///250	-700	1
        ///350	-900	1
        ///450	-700	2
        ///550	-900	0
        ///650	-700	1
        ///750	-900	1
        ///850	-700	0
        ///950	-900	2
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern2 {
            get {
                return ResourceManager.GetString("Pattern2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50	-100	1
        ///150	-300	2
        ///250	-100	0
        ///350	-300	2
        ///450	-100	1
        ///550	-300	2
        ///650	-100	2
        ///750	-300	0
        ///850	-100	1
        ///950	-300	2
        ///50	-400	1
        ///150	-600	0
        ///250	-400	2
        ///350	-600	2
        ///450	-400	4
        ///550	-600	2
        ///650	-400	1
        ///750	-600	2
        ///850	-400	0
        ///950	-600	2
        ///50	-700	2
        ///150	-900	1
        ///250	-700	0
        ///350	-900	2
        ///450	-700	2
        ///550	-900	0
        ///650	-700	2
        ///750	-900	1
        ///850	-700	2
        ///950	-900	0
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern3 {
            get {
                return ResourceManager.GetString("Pattern3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50	-100	0
        ///150	-130	1
        ///250	-160	2
        ///350	-190	1
        ///450	-220	0
        ///550	-250	1
        ///650	-280	2
        ///750	-310	0
        ///850	-340	1
        ///950	-370	2
        ///50	-400	0
        ///150	-430	1
        ///250	-460	2
        ///350	-490	1
        ///450	-520	0
        ///550	-550	2
        ///650	-580	1
        ///750	-610	0
        ///850	-640	2
        ///950	-670	1
        ///50	-700	2
        ///150	-730	0
        ///250	-760	1
        ///350	-790	2
        ///450	-820	0
        ///550	-850	1
        ///650	-880	0
        ///750	-910	2
        ///850	-940	0
        ///950	-970	1
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern4 {
            get {
                return ResourceManager.GetString("Pattern4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50	-100	0
        ///150	-130	1
        ///250	-160	2
        ///350	-190	1
        ///450	-220	0
        ///550	-250	1
        ///650	-280	2
        ///750	-310	0
        ///850	-340	1
        ///950	-370	2
        ///50	-400	0
        ///150	-430	1
        ///250	-460	2
        ///350	-490	1
        ///450	-520	4
        ///550	-550	2
        ///650	-580	1
        ///750	-610	0
        ///850	-640	2
        ///950	-670	1
        ///50	-700	2
        ///150	-730	0
        ///250	-760	1
        ///350	-790	2
        ///450	-820	0
        ///550	-850	1
        ///650	-880	0
        ///750	-910	2
        ///850	-940	0
        ///950	-970	1
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern5 {
            get {
                return ResourceManager.GetString("Pattern5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50	-100	0
        ///150	-130	1
        ///250	-160	2
        ///350	-190	1
        ///450	-220	0
        ///550	-250	1
        ///650	-280	2
        ///750	-310	0
        ///850	-340	1
        ///950	-370	2
        ///50	-400	0
        ///150	-430	1
        ///250	-460	2
        ///350	-490	1
        ///450	-520	3
        ///550	-550	2
        ///650	-580	1
        ///750	-610	0
        ///850	-640	2
        ///950	-670	1
        ///50	-700	2
        ///150	-730	0
        ///250	-760	1
        ///350	-790	2
        ///450	-820	0
        ///550	-850	1
        ///650	-880	0
        ///750	-910	2
        ///850	-940	0
        ///950	-970	1
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern6 {
            get {
                return ResourceManager.GetString("Pattern6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   950	-100	0
        ///850	-130	1
        ///750	-160	2
        ///650	-190	1
        ///550	-220	0
        ///450	-250	1
        ///350	-280	2
        ///250	-310	0
        ///150	-340	1
        ///50	-370	2
        ///950	-400	0
        ///850	-430	1
        ///750	-460	2
        ///650	-490	1
        ///550	-520	4
        ///450	-550	2
        ///350	-580	1
        ///250	-610	0
        ///150	-640	2
        ///050	-670	1
        ///950	-700	2
        ///850	-730	0
        ///750	-760	1
        ///650	-790	2
        ///550	-820	0
        ///450	-850	1
        ///350	-880	0
        ///250	-910	2
        ///150	-940	0
        ///50	-970	1
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern7 {
            get {
                return ResourceManager.GetString("Pattern7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   950	-100	0
        ///850	-130	1
        ///750	-160	2
        ///650	-190	1
        ///550	-220	0
        ///450	-250	1
        ///350	-280	2
        ///250	-310	0
        ///150	-340	1
        ///50	-370	2
        ///950	-400	0
        ///850	-430	1
        ///750	-460	2
        ///650	-490	1
        ///550	-520	3
        ///450	-550	2
        ///350	-580	1
        ///250	-610	0
        ///150	-640	2
        ///050	-670	1
        ///950	-700	2
        ///850	-730	0
        ///750	-760	1
        ///650	-790	2
        ///550	-820	0
        ///450	-850	1
        ///350	-880	0
        ///250	-910	2
        ///150	-940	0
        ///50	-970	1
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern8 {
            get {
                return ResourceManager.GetString("Pattern8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   950	-100	0
        ///850	-130	1
        ///750	-160	2
        ///650	-190	1
        ///550	-220	0
        ///450	-250	1
        ///350	-280	2
        ///250	-310	0
        ///150	-340	1
        ///50	-370	2
        ///950	-400	0
        ///850	-430	1
        ///750	-460	2
        ///650	-490	1
        ///550	-520	0
        ///450	-550	2
        ///350	-580	1
        ///250	-610	0
        ///150	-640	2
        ///050	-670	1
        ///950	-700	2
        ///850	-730	0
        ///750	-760	1
        ///650	-790	2
        ///550	-820	0
        ///450	-850	1
        ///350	-880	0
        ///250	-910	2
        ///150	-940	0
        ///50	-970	1
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Pattern9 {
            get {
                return ResourceManager.GetString("Pattern9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Player {
            get {
                object obj = ResourceManager.GetObject("Player", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Player2 {
            get {
                object obj = ResourceManager.GetObject("Player2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap RedObject {
            get {
                object obj = ResourceManager.GetObject("RedObject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
